name: Test

on:
  push:
    branches:
      - main
      - v*
      - dev-*
    paths:
      - "**/*.go"
      - "go.mod"
      - "go.sum"
      - ".github/workflows/test.yml"
  pull_request:
    types: [opened, synchronize, reopened]
    paths:
      - "**/*.go"
      - "go.mod"
      - "go.sum"
      - ".github/workflows/test.yml"
  workflow_dispatch:

jobs:
  test:
    strategy:
      fail-fast: false
    runs-on: ubuntu-latest
    container:
      image: archlinux/archlinux:base-devel
    steps:
      - name: Install dependencies
        run: |
          pacman -Syu --needed --noconfirm go protobuf git

      - uses: actions/checkout@v3

      - name: Check Go modules
        run: |
          go mod tidy
          git diff --exit-code go.mod go.sum
          go mod verify

      - name: Test
        run: |
          export PATH=$(go env GOPATH)/bin:${PATH}
          go install -v github.com/ory/go-acc@latest
          go-acc --covermode=atomic -o=coverage.txt ./...
